// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/lotto_draw_result/{drwNo}": {
            "get": {
                "description": "get lotto draw result by drwNo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "get lotto draw result",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "drwNo",
                        "name": "drwNo",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/models.LottoDrawResult"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.LottoDrawResult": {
            "type": "object",
            "properties": {
                "bnusNo": {
                    "type": "integer"
                },
                "drwNo": {
                    "type": "integer"
                },
                "drwNoDate": {
                    "type": "string"
                },
                "drwtNo1": {
                    "type": "integer"
                },
                "drwtNo2": {
                    "type": "integer"
                },
                "drwtNo3": {
                    "type": "integer"
                },
                "drwtNo4": {
                    "type": "integer"
                },
                "drwtNo5": {
                    "type": "integer"
                },
                "drwtNo6": {
                    "type": "integer"
                },
                "firstAccumamnt": {
                    "type": "integer"
                },
                "firstPrzwnerCo": {
                    "type": "integer"
                },
                "firstWinamnt": {
                    "type": "integer"
                },
                "returnValue": {
                    "type": "string"
                },
                "totSellamnt": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "golang Lotto Draw Result Sample API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
