// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using simpleLotto.data.repository;

#nullable disable

namespace simpleLotto.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("20250729035938_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("simpleLotto.data.model.GetLottoDrawResult", b =>
                {
                    b.Property<int>("drwNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("bnusNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("drwNoDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("drwtNo1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("drwtNo2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("drwtNo3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("drwtNo4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("drwtNo5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("drwtNo6")
                        .HasColumnType("INTEGER");

                    b.Property<long>("firstAccumamnt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("firstPrzwnerCo")
                        .HasColumnType("INTEGER");

                    b.Property<long>("firstWinamnt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("returnValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("totSellamnt")
                        .HasColumnType("INTEGER");

                    b.HasKey("drwNo");

                    b.ToTable("lottoDrawResults");
                });
#pragma warning restore 612, 618
        }
    }
}
